# Generated by Django 5.1.2 on 2024-10-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='ano',
            new_name='año',
        ),
    ]
